In [1]:
#importing Tensorflow

import tensorflow as tf

print (tf.__version__)

2.19.0


In [2]:
#creating a new tensor

scalar = tf.constant(7)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check the number of dimensions of a tenosr (ndim stands for number of dimensions)

scalar.ndim

0

In [7]:
#create a vector([10,10])

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#check the ndim for vecotr

vector.ndim

1

In [9]:
#create a matirx

matrix = tf.constant([[10,7],
                      [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
#create another matirx

matrix2 = tf.constant([[10., 7.],
                      [3., 2.],
                      [8., 9.]], dtype=tf.float16) #specify the data type with data type parameter


matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
#numbert of dimnesion in matirx2

matrix2.ndim

2

In [13]:
#lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3