In [2]:
#shuffle the order of elements in a tensory
#this is important when data set is populated with one item (ramen pictures in the exmaple of the tutorial) and then the predictions will be biased for that , so in that casee we need to shuffle the tensors
# this is valuble when you want to shuffle the data

import tensorflow as tf

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

#lets shuffle our non shuffled tensor
#in this case it randomly shuffles a tensor along with its first dimension , meaning it will only shuffle the tensor by changing the each array
tf.random.shuffle(not_shuffled)

not_shuffled2 = tf.constant([[20,40],
                             [30,60],
                             [45,90]])

tf.random.set_seed(42)                  #this is global level random seed
print(tf.random.shuffle(not_shuffled2)) # this is operational level random seed



tf.Tensor(
[[30 60]
 [45 90]
 [20 40]], shape=(3, 2), dtype=int32)


In [3]:
#other ways to make tensors:

tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [6]:
#create a tensor of all zeros

tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [7]:
#you can also turn numpy arrays into tesnors
#the main diffrenece betwen numpy arrays and tensor is that tensors can be run on a GPU (much fater for numerical computing)

import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A
#x = tf.constnant(some_matrix) #capital for matirx or tensor
#y = tf.constant(vector) #non-captial for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [11]:
A = tf.constant(numpy_A, shape=(2,3,4))
B= tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)