In [ ]:
import tensorflow as tf


#basic operations

#------------------1.addition---------------------

tesnor1 = tf.constant([[10,7], [3,4]])
print(tesnor1 + 10)
# when this happen original tensor is unchanged
print(tesnor1)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [ ]:
#-----------------2.multiplication-----------------
print(tesnor1 * 10)
#like this we can do the subsract too


tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


In [ ]:
#we can use tensorflow build in functiosn too

print(tf.multiply(tesnor1 , 12))
print(tf.add(tesnor1, 10))

# like this tf has some pre build functions

tf.Tensor(
[[120  84]
 [ 36  48]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
