In [ ]:
import tensorflow as tf

tensor1 = tf.constant([[10,7], [3,4]])
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#this is how we multply matrixes in tensor
tf.matmul(tensor1,tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# and note the diffrenece that when we ultiply it like this it only gives the element iwse multiplicatios

tensor1 * tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
#how to multipky matrixes with python operators

tensor1 @ tensor1

#in here @ is used to multiply matrixes in python

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#more exmaples
#create a tensor with shape (3,2)

x = tf.constant([[1,2],[3,4], [5,6]])
x.shape

#create another (3,2) shape tensor

y = tf.constant([[7,8], [9,10], [11,12]])
y.shape

#try to multiply of same shape
x @ y
tf.matmul(x,y)
#check this way we cannot multply matirxes in same shape
#why? because ever matirx has 3x2 shape so 3x2,3x2 canniot multply beacuse first tensors coulmns shoud match the second tensors rows number you know this

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# so we reshape the size of the matrix
tf.reshape(y, shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
#now ,ets multply them

print(tf.matmul(x, tf.reshape(y, shape=(2,3))))


# lets rehsopae x and multiply it
print(tf.matmul(tf.reshape(x, shape=(2,3)), y))


tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [ ]:
#transpose of a matrix (rows columns switch)

x, tf.transpose(x)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#The dot product
#matrix multplication as refrred as dot product
#we can perfomr matirx multiplication by
#----------1. tf.matmul()------------
#----------2. tf.tensordot()---------

#perform a dotproduct on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(x), y, axes=1)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#perform matrix multiplication between x and y (transposed)
tf.matmul(x , tf.transpose(y))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#perfomr matrix multiplication between x and y (reshape)
tf.matmul(x , tf.reshape(y, shape=(2,3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>