In [10]:
#Aggregating tensors = condensing them from multiple values down to a smaller amount of values

import tensorflow as tf
import numpy as np

#get absoulte values
A = tf.constant([-7,-10, -100, 17])
A

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  -7,  -10, -100,   17], dtype=int32)>

In [11]:
#this is how we take the absolute values form a given tensor
tf.abs(A)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  7,  10, 100,  17], dtype=int32)>

In [12]:
# lets go through the following dforms of aggregation
#---1. get the minimu
#---2. get the maximum
#---3. ge the mean of the tensor
#---4.get the sum of the tensor

# lets create a random tensor to chekc this

E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([91, 11, 96, 74, 55, 29, 89, 49, 42, 43, 13, 55, 91, 31, 74, 51, 38,
       50, 78, 14, 15, 86, 77, 89, 11, 44, 11, 47, 91, 19, 21, 34, 69, 17,
       42, 38, 32, 62, 98, 44, 67, 10, 52, 31, 84, 47, 74, 70, 96, 91])>

In [13]:
tf.size(E), E.shape,

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]))

In [14]:
#finding the minimum
tf.reduce_min(E)
# this is like np.min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=10>

In [15]:
#finding the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [16]:
#mean of the tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [17]:
#sum of the tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2643>

In [22]:
#finging the variance
#to find the variance we need tfp (tensorflow probabilty)

# in this case we use tf
import tensorflow_probability as tfp
tfp.stats.variance(E)
tfp.stats.stddev(tf.cast(E, tf.float32)) # and note that to find standered devaiation we should have flot type of data chatgpt example eke thiynwa meka hodt

#also we can use tf.math to search for std and variance
tf.math.reduce_variance(tf.cast(E, tf.float32)) # notice that in here also we had to make it as a float type
print(f" std dev is : {tf.math.reduce_std(tf.cast(E, tf.float32))}")

 std dev is : 27.596384048461914
