In [2]:
 #finding the positional maximum and minimum
import tensorflow as tf

tf.random.set_seed(42)
tensor1 = tf.random.uniform(shape=[50])
tensor1

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [3]:
# first lets see what is the maximum number of this tensor
tf.reduce_max(tensor1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
#find the positional maximum/argmax is the method we use to find the ositional maximum
tf.argmax(tensor1)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [5]:
#to check if the argmx gave the right answer lets check the 42th position value:
tensor1[42]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [8]:
#check for equality
tensor1[tf.argmax(tensor1)] == tf.reduce_max(tensor1)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [13]:
#so now lets check positioanl minimum

#before that we have to check what is the minimum value of this tesnor

minValue = tf.reduce_min(tensor1)

In [11]:
#now lets get the positional minimum with the relevant method :
tf.argmin(tensor1)


<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [16]:
#now lets check

tensor1[tf.argmin(tensor1)] == tf.reduce_min(tensor1)
tensor1[tf.argmin(tensor1)] == minValue

<tf.Tensor: shape=(), dtype=bool, numpy=True>