In [1]:
import tensorflow as tf

some_list = [0,1,2,3]

tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [2]:
#specify custom values for one hot encoding

tf.one_hot(some_list, depth=4, on_value="yo i love deep learning", off_value="i also like to play cricket")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'i also like to play cricket',
        b'i also like to play cricket', b'i also like to play cricket'],
       [b'i also like to play cricket', b'yo i love deep learning',
        b'i also like to play cricket', b'i also like to play cricket'],
       [b'i also like to play cricket', b'i also like to play cricket',
        b'yo i love deep learning', b'i also like to play cricket'],
       [b'i also like to play cricket', b'i also like to play cricket',
        b'i also like to play cricket', b'yo i love deep learning']],
      dtype=object)>

In [3]:
tf.one_hot(some_list, depth=4, on_value=3, off_value=9)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[3, 9, 9, 9],
       [9, 3, 9, 9],
       [9, 9, 3, 9],
       [9, 9, 9, 3]], dtype=int32)>