In [6]:
#tf.amth eke godak maths perators thiynwa, methnain katah krnne ethanin kiypayak
#squaring, log, square root

import tensorflow as tf

H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [7]:
#square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [9]:
#find the sqaure root (error ekk enna puluwan tensor eke data type eka int nm , int ewa me method ekt daanna bha )
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [11]:
#find the log (meketh ehmai int ewa bha float krla daanna one, flot wage thwa thiynwa data type eken accept krna ewa unath puluwan)

tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>