In [1]:
#tensors and numpy:- tesnorflow interacts beautifuly wiht numpy arrays

import tensorflow as tf
import numpy as np

#create a tensor directly form a numpy array
tensor1 = tf.constant(np.array([3., 7., 10.]))
tensor1

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [2]:
#convert ur tensor back to a nupy array
np.array(tensor1), type(np.array(tensor1))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [3]:
#another way to convert tesnor to a umpy array
tensor1.numpy(), type(tensor1.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [4]:
#the default type of each are slightly differenet
numpy_tensor1 = tf.constant(np.array([3., 7., 10.]))
tensor_tensor1 = tf.constant([3., 7., 10.])

#check the datatypes of each
numpy_tensor1.dtype, tensor_tensor1.dtype

(tf.float64, tf.float32)